services:
  mc:
    image: itzg/minecraft-server
    volumes:
      - dot-server:/data
    ports:
      - "25575:25565/tcp"
      # - "24454:24454/udp"
    environment:
      EULA: true
      type: PAPER
      ENABLE_AUTOPUSE: true
      SPIGET_RESOURCES: ${MC_PLUGINS}
      # MODRINTH_PROJECTS: "simple-voice-chat"
      MAX_TICK_TIME: "-1"
      VERSION: 1.21.3
      MEMORY: "3G"
      USE_AIKAR_FLAGS: true
      ENABLE_ROLLING_LOGS: true
      TZ: "America/Edmonton"
      OVERRIDE_SERVER_PROPERITES: "true"
      DIFFICULTY: "hard"
      WHITELIST: ${MC_WHITELIST}
      OPS: ${MC_OPS}
      VIEW_DISTANCE: 16
      HIDE_ONLINE_PLAYERS: true
      MAX_PLAYERS: 10
      PVP: true
      MOTD: ${MC_MOTD}
      # INITIAL_ENABLED_PACKS: "minecart_improvements,update_1_21,vanilla"

    restart: unless-stopped

volumes:
  dot-server: {}
