services:
  mc:
    image: itzg/minecraft-server
    volumes:
      - sushi:/data
    ports:
      - "25565:25565"
    environment:
      EULA: true
      ENABLE_AUTOPUSE: true
      MAX_TICK_TIME: "-1"
      TYPE: FORGE
      CF_API_KEY: ${CF_API_KEY}
      CURSEFORGE_FILES: ${CF_MODS}
      VERSION: 1.20.1
      MEMORY: "4G"
      USE_AIKAR_FLAGS: true
      ENABLE_ROLLING_LOGS: true
      TZ: "America/Edmonton"
      OVERRIDE_SERVER_PROPERITES: "true"
      DIFFICULTY: "hard"
      WHITELIST: ${MC_WHITELIST}
      OPS: ${MC_OPS}
      VIEW_DISTANCE: 16
      MAX_PLAYERS: 10
      PVP: "true"
      MOTD: ${MC_MOTD}

    restart: unless-stopped

volumes:
  sushi: {}
