services:
  plausible_db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 1m
    networks:
      - internal

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.12-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-plausible}_events_db
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - ./clickhouse/logs.xml:/etc/clickhouse-server/config.d/logs.xml:ro
      # This makes ClickHouse bind to IPv4 only, since Docker doesn't enable IPv6 in bridge networks by default.
      # Fixes "Listen [::]:9000 failed: Address family for hostname not supported" warnings.
      - ./clickhouse/ipv4-only.xml:/etc/clickhouse-server/config.d/ipv4-only.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1"]
      start_period: 1m

  plausible:
    image: ghcr.io/plausible/community-edition:v3.1.0
    container_name: ${COMPOSE_PROJECT_NAME:-plausible}_app
    restart: always
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      plausible_db:
        condition: service_healthy
      plausible_events_db:
        condition: service_healthy
    volumes:
      - plausible-data:/var/lib/plausible
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    labels:
      caddy_0: ${DOMAIN_0}
      caddy.reverse_proxy: "{{upstreams 8000}}"
      caddy.tls.dns: cloudflare {env.CF_API_TOKEN}
      caddy_1: ${DOMAIN_1}
      caddy.reverse_proxy: "{{upstreams 8000}}"
      caddy.tls.dns: cloudflare {env.CF_API_TOKEN}
    environment:
      - TMPDIR=/var/lib/plausible/tmp
      # Required
      - BASE_URL=${BASE_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_URL=postgres://postgres:postgres@plausible_db:5432/plausible_db
      - CLICKHOUSE_DATABASE_URL=http://plausible_events_db:8123/plausible_events_db
    networks:
      - internal
      - caddy

networks:
  internal:
    name: ${COMPOSE_PROJECT_NAME:-plausible}_internal
    driver: bridge
  caddy:
    external: true

volumes:
  db-data:
    name: ${COMPOSE_PROJECT_NAME:-plausible}_db_data
  event-data:
    name: ${COMPOSE_PROJECT_NAME:-plausible}_event_data
  event-logs:
    name: ${COMPOSE_PROJECT_NAME:-plausible}_event_logs
  plausible-data:
    name: ${COMPOSE_PROJECT_NAME:-plausible}_data