services:
  db:
    image: mariadb:latest
    container_name: ${COMPOSE_PROJECT_NAME}_db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_ROOT_HOST: localhost
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  wordpress:
    image: wordpress:latest
    container_name: ${COMPOSE_PROJECT_NAME}_app
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX:-wp_}
      # Security keys - required for consistent sessions across container restarts
      WORDPRESS_AUTH_KEY: ${WP_AUTH_KEY}
      WORDPRESS_SECURE_AUTH_KEY: ${WP_SECURE_AUTH_KEY}
      WORDPRESS_LOGGED_IN_KEY: ${WP_LOGGED_IN_KEY}
      WORDPRESS_NONCE_KEY: ${WP_NONCE_KEY}
      WORDPRESS_AUTH_SALT: ${WP_AUTH_SALT}
      WORDPRESS_SECURE_AUTH_SALT: ${WP_SECURE_AUTH_SALT}
      WORDPRESS_LOGGED_IN_SALT: ${WP_LOGGED_IN_SALT}
      WORDPRESS_NONCE_SALT: ${WP_NONCE_SALT}
      WORDPRESS_CONFIG_EXTRA: |
        /* =================================================================
         * REVERSE PROXY CONFIGURATION (Cloudflare + Caddy)
         * ================================================================= */

        /* Real Client IP - Cloudflare passes original IP in CF-Connecting-IP,
         * Caddy passes it in X-Forwarded-For. Check both. */
        if (isset($$_SERVER['HTTP_CF_CONNECTING_IP'])) {
            $$_SERVER['REMOTE_ADDR'] = $$_SERVER['HTTP_CF_CONNECTING_IP'];
        } elseif (isset($$_SERVER['HTTP_X_FORWARDED_FOR'])) {
            $$ips = explode(',', $$_SERVER['HTTP_X_FORWARDED_FOR']);
            $$_SERVER['REMOTE_ADDR'] = trim($$ips[0]);
        }

        /* HTTPS Detection - Trust X-Forwarded-Proto from Caddy */
        if (isset($$_SERVER['HTTP_X_FORWARDED_PROTO']) && $$_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
            $$_SERVER['HTTPS'] = 'on';
            $$_SERVER['SERVER_PORT'] = 443;
        }

        /* Force SSL for admin - we're behind HTTPS proxy */
        define('FORCE_SSL_ADMIN', true);

        /* Site URLs - set in environment or use defaults */
        if (getenv('WP_HOME')) {
            define('WP_HOME', getenv('WP_HOME'));
            define('WP_SITEURL', getenv('WP_SITEURL') ?: getenv('WP_HOME'));
        }

        /* =================================================================
         * SECURITY HARDENING
         * ================================================================= */
        define('DISALLOW_FILE_EDIT', true);
        define('WP_AUTO_UPDATE_CORE', 'minor');

        /* =================================================================
         * PERFORMANCE
         * ================================================================= */
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_MAX_MEMORY_LIMIT', '512M');
        define('WP_POST_REVISIONS', 5);
        define('AUTOSAVE_INTERVAL', 300);
        define('EMPTY_TRASH_DAYS', 14);

        /* =================================================================
         * DEBUG MODE - Set WP_DEBUG_MODE=true in environment to enable
         * ================================================================= */
        $$debug_mode = (getenv('WP_DEBUG_MODE') === 'true');
        define('WP_DEBUG', $$debug_mode);
        define('WP_DEBUG_LOG', $$debug_mode);
        define('WP_DEBUG_DISPLAY', false);

    volumes:
      - wordpress_data:/var/www/html
    labels:
      caddy: ${WP_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls.dns: cloudflare ${CF_API_TOKEN}
    networks:
      - internal
      - caddy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/wp-admin/install.php || curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  internal:
    name: ${COMPOSE_PROJECT_NAME}_internal
    driver: bridge
  caddy:
    external: true

volumes:
  db_data:
    name: ${COMPOSE_PROJECT_NAME}_db_data
  wordpress_data:
    name: ${COMPOSE_PROJECT_NAME}_wp_data