services:
  db:
    image: mariadb:latest
    container_name: ${COMPOSE_PROJECT_NAME:-wordpress}_db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_ROOT_HOST: localhost
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_internal
    # Health check to ensure database is ready before WordPress starts
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  wordpress:
    image: wordpress:latest
    container_name: ${COMPOSE_PROJECT_NAME:-wordpress}_app
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Database connection
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX:-wp_}

      # Debug mode - set WP_DEBUG_MODE=true in .env to enable WordPress debugging
      # Debug logs are written to /var/www/html/wp-content/debug.log
      WP_DEBUG_MODE: ${WP_DEBUG_MODE:-false}

      # Security keys and salts (generate unique values!)
      WORDPRESS_AUTH_KEY: ${WP_AUTH_KEY}
      WORDPRESS_SECURE_AUTH_KEY: ${WP_SECURE_AUTH_KEY}
      WORDPRESS_LOGGED_IN_KEY: ${WP_LOGGED_IN_KEY}
      WORDPRESS_NONCE_KEY: ${WP_NONCE_KEY}
      WORDPRESS_AUTH_SALT: ${WP_AUTH_SALT}
      WORDPRESS_SECURE_AUTH_SALT: ${WP_SECURE_AUTH_SALT}
      WORDPRESS_LOGGED_IN_SALT: ${WP_LOGGED_IN_SALT}
      WORDPRESS_NONCE_SALT: ${WP_NONCE_SALT}
      
      # Extra wp-config.php settings for Cloudflare/reverse proxy compatibility
      # and security hardening
      WORDPRESS_CONFIG_EXTRA: |
        /* Cloudflare/Reverse Proxy HTTPS Detection */
        /* Trust X-Forwarded-Proto header from Cloudflare Tunnel */
        if (isset($$_SERVER['HTTP_X_FORWARDED_PROTO']) && $$_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
            $$_SERVER['HTTPS'] = 'on';
        }

        /* FORCE_SSL_ADMIN disabled - Cloudflare Tunnel handles HTTPS termination.
         * The tunnel connects to WordPress over HTTP internally, so forcing SSL
         * here causes redirect loops. HTTPS is enforced at the Cloudflare edge. */
        define('FORCE_SSL_ADMIN', false);

        /* Site URLs - Set via environment or database */
        if (getenv('WP_HOME')) {
            define('WP_HOME', getenv('WP_HOME'));
            define('WP_SITEURL', getenv('WP_SITEURL') ?: getenv('WP_HOME'));
        }

        /* Security Hardening */
        define('DISALLOW_FILE_EDIT', true);
        define('WP_AUTO_UPDATE_CORE', 'minor');

        /* Performance */
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_MAX_MEMORY_LIMIT', '512M');

        /* Debug Mode - Configurable via WP_DEBUG_MODE environment variable */
        /* Set WP_DEBUG_MODE=true in .env to enable debugging */
        $$debug_mode = (getenv('WP_DEBUG_MODE') === 'true');
        define('WP_DEBUG', $$debug_mode);
        define('WP_DEBUG_LOG', $$debug_mode);
        define('WP_DEBUG_DISPLAY', false);  /* Never display errors to browser */

        /* Limit post revisions to save database space */
        define('WP_POST_REVISIONS', 5);
        define('AUTOSAVE_INTERVAL', 300);

        /* Trash auto-empty (days) */
        define('EMPTY_TRASH_DAYS', 14);

    volumes:
      # Persist WordPress files
      - wordpress_data:/var/www/html
      # Optional: Mount custom uploads.ini for larger file uploads
      # - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
    networks:
      - wordpress_internal
    ports:
      - "$0.0.0.0:{DEBUG_PORT:-8080}:80" # DEBUG 
    healthcheck:
      # Note: WordPress image doesn't include curl. Using PHP to check health.
      test: ["CMD-SHELL", "php -r 'exit(file_get_contents(\"http://localhost/\") ? 0 : 1);' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  # ==========================================================================
  # CLOUDFLARE TUNNEL: Secure exposure without port forwarding
  # ==========================================================================
  # cloudflared:
  #   image: cloudflare/cloudflared:latest
  #   container_name: ${COMPOSE_PROJECT_NAME:-wordpress}_tunnel
  #   restart: unless-stopped
  #   security_opt:
  #     - no-new-privileges:true
  #   # Use token-based authentication (configure tunnel in Cloudflare Zero Trust dashboard)
  #   command: tunnel --no-autoupdate run
  #   environment:
  #     TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
  #   networks:
  #     - wordpress_internal
  #   depends_on:
  #     wordpress:
  #       condition: service_healthy
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 128M
  #       reservations:
  #         memory: 64M

# =============================================================================
# NETWORKS: Isolated internal network (no external exposure)
# =============================================================================
networks:
  wordpress_internal:
    name: ${COMPOSE_PROJECT_NAME:-wordpress}_network
    driver: bridge
    internal: false  # Set to true if you want complete isolation (no internet from containers)

# =============================================================================
# VOLUMES: Persistent data storage
# =============================================================================
volumes:
  db_data:
    name: ${COMPOSE_PROJECT_NAME:-wordpress}_db_data
  wordpress_data:
    name: ${COMPOSE_PROJECT_NAME:-wordpress}_wp_data